import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { Alegreya, Mulish } from 'next/font/google';
import "./globals.css";
import { cookies } from "next/headers";



const mulish = Mulish({
  subsets: ['latin'],
  variable: '--font-mulish'
})

const alegreya = Alegreya({
  subsets: ['latin'],
  variable: '--font-alegreya'
})


export const metadata: Metadata = {
  title: "Twitter con Next.js",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const loggedUsername = (await cookies()).get('SocialUsername')

  return (
    <html lang="en" className={`${mulish.variable} ${alegreya.variable}`}>
      <body
        className={`antialiased`}
      >
        <Navbar loggedUsername={loggedUsername?.value} />
        {children}
      </body>
    </html>
  );
}
