import type { Metadata } from "next";
import localFont from "next/font/local";
import { Alegreya, Mulish } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/layout/Navbar";



const mulish = Mulish({
  subsets: ['latin'],
  variable: '--font-mulish'
})

const alegreya = Alegreya({
  subsets: ['latin'],
  variable: '--font-alegreya'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mulish.variable} ${alegreya.variable}`}>
      <body
        className={`antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
